apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: email-alerts
  namespace: monitoring
  labels:
    alertmanagerConfig: email-alerts

spec:
  route:
    receiver: gmail-email
    groupBy:
      - alertname
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 1h

  receivers:
    - name: gmail-email
      emailConfigs:
        - to: "krishna.singa05@gmail.com"
          from: "krishna.singa05@gmail.com"

          smarthost: "smtp.gmail.com:587"

          authUsername: "krishna.singa05@gmail.com"

          authPassword:
            name: alertmanager-gmail-secret
            key: app-password

          requireTLS: true
          sendResolved: true