apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-test-alert
  namespace: monitoring
  labels:
    release: kps

spec:
  groups:
    - name: kubernetes.test.rules
      rules:
        - alert: AssignmentTestAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Alertmanager email test"
            description: "Synthetic alert used to validate the alerting pipeline."