kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-cni-lab

networking:
  disableDefaultCNI: true
  kubeProxyMode: iptables
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"

kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        - name: bind-address
          value: "0.0.0.0"
    scheduler:
      extraArgs:
        - name: bind-address
          value: "0.0.0.0"
    etcd:
      local:
        extraArgs:
          - name: listen-metrics-urls
            value: "http://0.0.0.0:2381"

  - |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    metricsBindAddress: "0.0.0.0"

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      - containerPort: 30030
        hostPort: 30030
        protocol: TCP

  - role: worker
  - role: worker
