apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: probe-pvc
  namespace: storage-probe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 512Mi