fullnameOverride: kps

prometheus:
  service:
    type: NodePort
    nodePort: 30090

  prometheusSpec:
    retention: 6h
    retentionSize: 5GB
    scrapeInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 1800Mi

grafana:
  adminUser: admin
  adminPassword: admin

  defaultDashboardsEnabled: false

  service:
    type: NodePort
    nodePort: 30030

  persistence:
    enabled: true
    type: pvc
    storageClassName: openebs-hostpath
    size: 2Gi

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true

    datasources:
      enabled: true
      searchNamespace: ALL

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true

kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true

kubeProxy:
  service:
    port: 10249
    targetPort: 10249

kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
  serviceMonitor:
    scheme: http

kubelet:
  serviceMonitor:
    cAdvisor: true
    probes: true
    resource: true
    resourcePath: /metrics/resource